/* BY SUBMITTING THIS FILE TO CARMEN, I CERTIFY THAT I HAVE
 * PERFORMED ALL OF THE WORK TO CREATE THIS FILE AND/OR
 * DETERMINE THE ANSWERS FOUND WITHIN THIS FILE MYSELF WITH NO
 * ASSISTANCE FROM ANY PERSON (OTHER THAN THE INSTRUCTOR OR
 * GRADERS OF THIS COURSE) AND I HAVE STRICTLY ADHERED TO THE
 * TENURES OF THE OHIO STATE UNIVERSITY’S ACADEMIC INTEGRITY
 * POLICY.
 */

/* Author: Gavin Shi */
#include <stdio.h>
#include "mymultlib.h"

int main()
{
    printf("%i\n", multIntegers(1, 2));
    printf("%f\n", multFloats(2.24, 2.35));
    printf("%f\n", multDoubles(4.55, 1.55));

    return 0;
}